---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a new pull request, performs build and runs tests
name: 'Python Build/Test/Release'

# yamllint disable-line rule:truthy
on:
  # Trigger on tag push events
  push:
    tags:
      - '**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-validate:
    name: 'Validate Tag Push'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 1
    outputs:
      tag: "${{ steps.tag-validate.outputs.tag }}"
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - name: 'Verify Pushed Tag'
        id: 'tag-validate'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-push-verify-action@f9c6e753870c6405883be2ba18af05d075aaffe8 # v0.1.0
        with:
          versioning: 'semver'

  python-build:
    name: 'Python Build'
    needs: 'tag-validate'
    runs-on: 'ubuntu-latest'
    outputs:
      matrix_json: "${{ steps.python-build.outputs.matrix_json }}"
      artefact_name: "${{ steps.python-build.outputs.artefact_name }}"
      artefact_path: "${{ steps.python-build.outputs.artefact_path }}"
    permissions:
      contents: read
      id-token: write       # Needed for attestations
      attestations: write   # Needed for attestations
    timeout-minutes: 12
    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Python with enhanced caching
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-docker.txt
            pyproject.toml

      # Cache PDM dependencies for release build
      - name: Cache PDM release dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/pdm
            .pdm-python
            .venv
          key: pdm-release-${{ runner.os }}-python-3.11-${{ hashFiles('pyproject.toml', 'pdm.lock') }}
          restore-keys: |
            pdm-release-${{ runner.os }}-python-3.11-
            pdm-release-${{ runner.os }}-

      - name: 'Build Python project'
        id: 'python-build'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-build-action@8febd88cda1d708cf5066c175f7ac165c6b3bcf3 # v0.1.14
        with:
          sigstore_sign: true
          attestations: true

  python-tests:
    name: 'Python Tests'
    runs-on: 'ubuntu-latest'
    needs: 'python-build'
    # Matrix job
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.python-build.outputs.matrix_json) }}"
    permissions:
      contents: read
    timeout-minutes: 12
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Python with comprehensive caching
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-docker.txt
            pyproject.toml

      # Cache PDM dependencies for release test environment
      - name: Cache PDM release test dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/pdm
            .pdm-python
            .venv
          key: pdm-release-test-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'pdm.lock') }}
          restore-keys: |
            pdm-release-test-${{ runner.os }}-python-${{ matrix.python-version }}-
            pdm-release-test-${{ runner.os }}-

      - name: 'Test Python project [PYTEST]'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-test-action@bdde9e4e6221e858359f9036bd4f41ab3b1af90e # v0.1.11
        with:
          python_version: "${{ matrix.python-version }}"

  python-audit:
    name: 'Python Audit'
    runs-on: 'ubuntu-latest'
    needs: 'python-build'
    # Matrix job
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.python-build.outputs.matrix_json) }}"
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Python with comprehensive caching
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-docker.txt
            pyproject.toml

      # Cache PDM dependencies for release audit environment
      - name: Cache PDM release audit dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/pdm
            .pdm-python
            .venv
          key: pdm-release-audit-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'pdm.lock') }}
          restore-keys: |
            pdm-release-audit-${{ runner.os }}-python-${{ matrix.python-version }}-
            pdm-release-audit-${{ runner.os }}-

      - name: 'Audit Python project'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-audit-action@bab5316468c108870eb759ef0de622bae9239aad # v0.2.2
        with:
          python_version: "${{ matrix.python-version }}"

  test-pypi:
    name: 'Test PyPI Publishing'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'python-tests'
      - 'python-audit'
    environment:
      name: 'development'
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Python with pip caching for PyPI operations
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-docker.txt
            pyproject.toml

      - name: 'Test PyPI publishing'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/pypi-publish-action@81a056957ed050f8305760055b1fd8103a916989 # v0.1.1
        with:
          environment: 'development'
          tag: "${{ needs.tag-validate.outputs.tag }}"

  pypi:
    name: 'Release PyPI Package'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'test-pypi'
    environment:
      name: 'production'
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Python with pip caching for PyPI operations
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-docker.txt
            pyproject.toml

      - name: 'PyPI release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/pypi-publish-action@81a056957ed050f8305760055b1fd8103a916989 # v0.1.1
        with:
          environment: 'production'
          attestations: true
          tag: "${{ needs.tag-validate.outputs.tag }}"

  promote-release:
    name: 'Promote Draft Release'
    # yamllint disable-line rule:line-length
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - 'tag-validate'
      - 'pypi'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write # IMPORTANT: needed to edit a draft release and promote it
    timeout-minutes: 2
    outputs:
      release_url: "${{ steps.promote-release.outputs.release_url }}"
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Promote draft release'
        id: 'promote-release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/draft-release-promote-action@d7e7df12e32fa26b28dbc2f18a12766482785399 # v0.1.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.tag-validate.outputs.tag }}"
          latest: true

  # Need to attach build artefacts to the release
  # This step could potentially be moved
  # (May be better to when/where the release is still in draft state)
  attach-artefacts:
    name: 'Attach Artefacts to Release'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'python-build'
      - 'promote-release'
    permissions:
      contents: write # IMPORTANT: needed to edit the release and attach artefacts
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: 'audit'

      # Note: no need for a checkout step in this job

      - name: '⬇ Download build artefacts'
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: "${{ needs.python-build.outputs.artefact_name }}"
          path: "${{ needs.python-build.outputs.artefact_path }}"

      - name: 'Attach build artefacts to release'
        # yamllint disable-line rule:line-length
        uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          asset_paths: '["${{ needs.python-build.outputs.artefact_path }}/**"]'
