---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "Security Scans"
on:
  workflow_dispatch:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: "31 3 * * 0"
  push:
    branches: ["main", "master"]
    paths:
      - "**"
      - "!.github/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonatype-lifecycle:
    name: "Sonatype Lifecycle"
    permissions:
      contents: read  # Reusable scan job checks out the repo
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-sonatype-lifecycle.yaml@f7aae218f1fa0257e3dcd19f5c7d3f88f482f266 # v0.10.1
    secrets:
      NEXUS_IQ_PASSWORD: ${{ secrets.NEXUS_IQ_PASSWORD }}

  # Scan results are found at: https://sonarcloud.io/login
  sonarqube-cloud:
    name: "SonarQube Cloud"
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-sonarqube-cloud.yaml@dd7e7f1359ca34ca29a409354fcc648b4ec7a561 # v0.10.2
    permissions:
      contents: read  # Reusable scan job checks out the repo
      security-events: write  # Upload results to the code-scanning dashboard
      id-token: write  # Publish results and obtain a badge via OIDC
      # Uncomment the permission below if installing in a private repository.
      # actions: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
